name: vm
description: VM specific Dart code and helper scripts
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: "^2.7.0"

dependencies:
  build_integration:
    path: ../build_integration
  front_end: ^0.1.6
  kernel: ^0.3.6

dev_dependencies:
  args: ^1.4.4
