name: js
version: 0.6.3-dev
description: Annotations to create static Dart interfaces for JavaScript APIs.
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/js

environment:
  sdk: '>=2.9.0-1 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
