name: meta
version: 1.2.0-nnbd
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/meta
description: >
 This library contains the definitions of annotations that provide additional
 semantic information about the program being annotated. These annotations are
 intended to be used by tools to provide a better user experience.
environment:
  # This must remain a tight constraint (only allow dev versions) until nnbd is
  # stable.
  sdk: '>=2.9.0-18.0 <2.9.0'
