name: frontend_server
description: A resident kernel compiler
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: "^2.7.0"

dependencies:
  build_integration:
    path: ../build_integration
  vm:
    path: ../vm
  dev_compiler:
    path: ../dev_compiler
  front_end: ^0.1.6
  kernel: ^0.3.6
  args: ^1.4.4
  package_config: ^1.9.0

dev_dependencies:
  test: any
